apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-application-credentials
  namespace: kube-gce-cleanup
spec:
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: google-application-credentials
    template:
      type: Opaque
      data:
        credential.json: "{{ .credential }}"
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  data:
  - secretKey: credential
    remoteRef: 
      key: google-application-credentials
